name: test vim lang files
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Preparation
        run: sudo apt install gettext
      - name: Checkout
        uses: actions/checkout@v5
      - name: Checkout vim
        uses: actions/checkout@v5
        with:
          repository: 'vim/vim'
          path: vim
      - name: Build vim
        run: |
          cd vim/src
          # in vim
          ./configure --enable-gui=no
          # Github hosted runner
          # rel : https://docs.github.com/ja/actions/using-github-hosted-runners/about-github-hosted-runners
          # CPU 2core/2thread?
          make -j 2 vim

          cd ../..
          ${GITHUB_WORKSPACE}/vim/src/vim  --version
      - name: Test translation files
        run: |
          make test VIM=${GITHUB_WORKSPACE}/vim/src/vim
